### ISSUE TITLE
error: implicit declaration of function ‘bpf_prog_run’

### ISSUE THREAD

**Issue by GitMaggie** [Asphaltt/iptables-trace#1]
## Error when compiling : 

`#make
cd kernel && make
make[1]: Entering directory '/xxxxxx/iptable/iptables-trace-main/kernel'
make -C /lib/modules/5.10.134-16.3.al8.x86_64/build M=/xxxxxxx/iptable/iptables-trace-main/kernel modules
make[2]: Entering directory '/usr/src/kernels/5.10.134-16.3.al8.x86_64'
  CC [M]  /xxxxxx/iptable/iptables-trace-main/kernel/iptables-trace.o
/xxxxxx/iptable/iptables-trace-main/kernel/iptables-trace.c: In function ‘__run_bpf_prog_entry’:
/xxxxxxx/iptable/iptables-trace-main/kernel/iptables-trace.c:78:14: error: implicit declaration of function ‘bpf_prog_run’; did you mean ‘bpf_prog_put’? [-Werror=implicit-function-declaration]
   78 |     return !!bpf_prog_run(__ipt_bpf_prog_entry, regs);
      |              ^~~~~~~~~~~~
      |              bpf_prog_put
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:286: /xxxxxxx/iptable/iptables-trace-main/kernel/iptables-trace.o] Error 1
make[2]: *** [Makefile:1834: /xxxxxxx/iptable/iptables-trace-main/kernel] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.10.134-16.3.al8.x86_64'
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/xxxxxxx/iptable/iptables-trace-main/kernel'
make: *** [Makefile:7: kernel] Error 2

## OS/kernel version:
`# uname -a
Linux iZ2ze0r57pg9i6b1xhf8e0Z 5.10.134-16.3.al8.x86_64 #1 SMP Tue Mar 26 18:54:05 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

## module: xt_TRACE  is loaded
`# grep CONFIG_NETFILTER_XT_TARGET_TRACE /boot/config-$(uname -r)
CONFIG_NETFILTER_XT_TARGET_TRACE=m

`# lsmod | grep xt_TRACE
xt_TRACE               16384  0

**Comment by Asphaltt** [comment]
Can you check `grep BPF /boot/config-$(uname -r)`?

The kernel must be built with BPF CONFIGs.

**Comment by GitMaggie** [comment]
> Can you check `grep BPF /boot/config-$(uname -r)`?
> 
> The kernel must be built with BPF CONFIGs.

by the way, pwru is working fine in this node . but not iptables-trace. 
pls check the config as below : 

‘# grep BPF /boot/config-$(uname -r)
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_LSM=y
CONFIG_BPF_SYSCALL=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
‘# CONFIG_BPF_PRELOAD is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
’# CONFIG_BPFILTER is not set
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
‘# CONFIG_BPF_KPROBE_OVERRIDE is not set
CONFIG_TEST_BPF=m

**Comment by Asphaltt** [comment]
Can you try the PR #2 ?

**Comment by GitMaggie** [comment]
> Can you try the PR #2 ?

Thanks for your quick reply!  I tried with PR#2,  the previous issue is gone, but I got new issue with a warning regarding  x86  .
  

### Here is the output for  "make" : 

[root@xxxx iptables-trace-fix-bpf_prog_run]# make
cd kernel && make
make[1]: Entering directory '/iptables-trace-fix-bpf_prog_run/kernel'
make -C /lib/modules/5.10.134-16.3.al8.x86_64/build M=/iptables-trace-fix-bpf_prog_run/kernel modules
make[2]: Entering directory '/usr/src/kernels/5.10.134-16.3.al8.x86_64'
make[2]: Leaving directory '/usr/src/kernels/5.10.134-16.3.al8.x86_64'
make[1]: Leaving directory '/iptables-trace-fix-bpf_prog_run/kernel'
go generate && go build
In file included from /iptables-trace-fix-bpf_prog_run/ebpf/iptables-trace.c:2:
./ebpf/headers/bpf_kprobe_args.h:43:2: warning: use of a '#elifdef' directive is a C2x extension [-Wc2x-extensions]
#elifdef __TARGET_ARCH_x86
 ^
1 warning generated.
Compiled /iptables-trace-fix-bpf_prog_run/iptablestrace_bpfel.o
Stripped /iptables-trace-fix-bpf_prog_run/iptablestrace_bpfel.o
Wrote /iptables-trace-fix-bpf_prog_run/iptablestrace_bpfel.go
In file included from /iptables-trace-fix-bpf_prog_run/ebpf/iptables-trace.c:2:
./ebpf/headers/bpf_kprobe_args.h:43:2: warning: use of a '#elifdef' directive is a C2x extension [-Wc2x-extensions]
#elifdef __TARGET_ARCH_x86
 ^
1 warning generated.
Compiled /iptables-trace-fix-bpf_prog_run/iptablestrace_bpfeb.o
Stripped /iptables-trace-fix-bpf_prog_run/iptablestrace_bpfeb.o
Wrote /iptables-trace-fix-bpf_prog_run/iptablestrace_bpfeb.go


### Then I got error  : 
 ./iptables-trace 
2024/10/30 20:59:04 Failed to check kernel version: failed to parse kernel version: Invalid character(s) found in prerelease "x86_64"

###  uname -a
Linux  xxxx  5.10.134-16.3.al8.x86_64 #1 SMP Tue Mar 26 18:54:05 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

### uname -m
x86_64

**Comment by Asphaltt** [comment]
> Thanks for your quick reply! 

You are welcome.

> 5.10.134-16.3.al8.x86_64

Aha, I see. It's because the semver library is unable to parse such kernel version.

I add an enhancement to parse kernel version.

You can try the PR #3.
